#!/bin/bash
set -e

echo "=== ⚔️ Crucible Game Server Startup ==="

BRANCH="${GIT_BRANCH:-main}"
REPO_URL="${GIT_ADDRESS:-https://github.com/Flurben/Crucible.git}"

echo "Working directory: $(pwd)"
echo "Current user: $(whoami 2>/dev/null || id -un 2>/dev/null || echo 'container')"

# Configure safe.directory for Git 2.35+
git config --global --add safe.directory "*" 2>/dev/null || true

# Force fetch and reset to latest origin commit if git repository exists
if [ -d ".git" ]; then
    echo "Syncing with Git repository (${REPO_URL} branch: ${BRANCH})..."
    git remote set-url origin "${REPO_URL}" 2>/dev/null || git remote add origin "${REPO_URL}" 2>/dev/null || true
    git fetch origin "${BRANCH}" 2>/dev/null || echo "Git fetch warning: proceeding with existing files"
    git reset --hard "origin/${BRANCH}" 2>/dev/null || echo "Git reset warning: proceeding with existing files"
elif [ -n "${GIT_ADDRESS}" ]; then
    echo "Cloning Git repository (${GIT_ADDRESS} branch: ${BRANCH})..."
    git clone -b "${BRANCH}" "${GIT_ADDRESS}" . 2>/dev/null || echo "Git clone warning: proceeding with existing files"
fi

if [ ! -f "package.json" ]; then
    echo "ERROR: package.json missing in $(pwd)!"
    ls -la
    exit 1
fi

echo "Installing npm dependencies..."
npm install

echo "Building shared package..."
npm run build -w shared

echo "Building client package..."
npm run build -w client 2>/dev/null || true

echo "Building server package..."
npm run build -w server

# Verify that server build output exists
if [ ! -f "server/dist/index.js" ]; then
    echo "WARNING: server/dist/index.js was not generated by tsc. Running tsx fallback..."
    echo "Starting Crucible Colyseus Server using tsx on port ${PORT:-${SERVER_PORT:-2567}}..."
    exec npx tsx server/src/index.ts
else
    echo "Starting Crucible Colyseus Server (dist/index.js) on port ${PORT:-${SERVER_PORT:-2567}}..."
    exec npm run start -w server
fi






